# from dataclasses import asdict

from fastapi import Depends, FastAPI, HTTPException
from sqlalchemy.orm import Session

from database import create_tables
from repository import (
    _task_model_to_task,
    create_task,
    delete_task,
    get_all_tasks,
    get_database_session,
    get_task_by_id,
    update_task,
     update_task_title
)
from schemas import TaskCreate, TaskListResponse, TaskResponse, TaskUpdate
from tasks import Task  # TaskList

app = FastAPI(
    title="Task Manager API",
    version="1.0.0",
    description=(
        "A simple task manager built with FastAPI and PostgreSQL.\n\n"
        "Tasks can be created, listed, completed, retitled and deleted. "
        "Each task has an id, a title (1-30 characters), a done flag and "
        "a creation timestamp."
    ),
    openapi_tags=[
        {"name": "health", "description": "Service health check."},
        {"name": "tasks", "description": "Create, read, update and delete tasks."},
    ],
)

NOT_FOUND_RESPONSE = {404: {"description": "Task not found"}}


@app.on_event("startup")
def startup():
    create_tables()


@app.get("/", tags=["health"], summary="Health check")
def root():
    """Return `{"status": "ok"}` when the API is up."""
    return {"status": "ok"}


@app.get(
    "/tasks",
    response_model=TaskListResponse,
    tags=["tasks"],
    summary="List all tasks",
)
def list_tasks(db: Session = Depends(get_database_session)):
    """Return every stored task."""
    tl = get_all_tasks(db)
    return {"tasks": tl._tasks}


@app.get(
    "/tasks/{task_id}",
    response_model=TaskResponse,
    tags=["tasks"],
    summary="Get a task by id",
    responses=NOT_FOUND_RESPONSE,
)
def get_task(task_id: str, db: Session = Depends(get_database_session)):
    """Return a single task, or 404 if no task has the given id."""
    try:
        task = get_task_by_id(db, task_id)
        return task
    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found")


@app.post(
    "/tasks",
    status_code=201,
    response_model=TaskResponse,
    tags=["tasks"],
    summary="Create a task",
    responses={400: {"description": "Task could not be created"}},
)
def create_new_task(payload: TaskCreate, db: Session = Depends(get_database_session)):
    """
    Create a new task from a title (1-30 characters).
    The task starts with `done` set to false; its id and `created_at`
    timestamp are generated by the server.
    """
    try:
        dummy_id = "123"
        task = Task(title=payload.title, user_id=dummy_id)
        create_task(db, task)
        return task
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.patch(
    "/tasks/{task_id}/complete",
    response_model=TaskResponse,
    tags=["tasks"],
    summary="Mark a task as complete",
    responses=NOT_FOUND_RESPONSE,
)
def complete_task(task_id: str, db: Session = Depends(get_database_session)):
    """Set the task's `done` flag to true and return the updated task."""
    try:
        update_task(db, task_id)

        return get_task_by_id(db, task_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found")


@app.delete(
    "/tasks/{task_id}",
    status_code=204,
    tags=["tasks"],
    summary="Delete a task",
    responses=NOT_FOUND_RESPONSE,
)
def remove_task(task_id: str, db: Session = Depends(get_database_session)):
    """Delete a task permanently. Returns 204 with no body on success."""
    try:
        delete_task(db, task_id)

    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found")


@app.patch(
    "/tasks/{task_id}/title",
    response_model=TaskResponse,
    tags=["tasks"],
    summary="Rename a task",
    responses=NOT_FOUND_RESPONSE,
)
def change_task_title(
    task_id: str,
    payload: TaskUpdate,
    db: Session = Depends(get_database_session),
):
    """Replace the task's title and return the updated task."""
    try:
        update_task_title(db, task_id, payload.title)

        return get_task_by_id(db, task_id)

    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found")
