services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: tasks
      POSTGRES_DB: tasks
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
 
volumes:
  postgres_data:
